name = "nuxt-image-gall-3o1m"
pages_build_output_dir = "/dist"

[env.production]
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]
# [[env.production.analytics_engine_datasets]]
# binding = "ANALYTICS"
# dataset = "nuxt_image_gall_3o1m"

# [[env.production.r2_buckets]]
# binding = "BLOB"
# bucket_name = "nuxt-image-gall-3o1m"

# [[env.production.kv_namespaces]]
# binding = "CACHE"
# id = "22ac9b3eccbd4baaa57886f9f18003ad"

# [[env.production.d1_databases]]
# database_id = "a69ccde7-a0d6-4d38-af7b-8cea0955ff83"
# binding = "DB"
# database_name = "DB"

# [[env.production.kv_namespaces]]
# binding = "KV"
# id = "2c5369e6a5f449498ac2f09abb5886c7"
